### ISSUE TITLE
Can't find simulated_data

### ISSUE THREAD

**Issue by Mind-Insight** [chloechsu/nanoparticle#2]

**Comment by Mind-Insight** [comment]
@smglsn12 @chloechsu I tried to build yours project, but I can't find simulated data in the link, that you gave in repo

**Comment by smglsn12** [comment]
Thank you for reaching out! This is a clarity issue on my part, the
file "Cu_reproducable_alignment_df_extracted_110222.joblib"
is a dataframe containing the simulated data. Use the paper_files
notebook to load this dataframe! After running the 4th cell, you can
call "test_rf_obj.spectra_df"
to see the full dataframe, or you can just load it directly without using
the analysis object defined in the 4th cell.

If you're looking for the raw feff output, that is contained in the
"dataset generation" folder. The raw feff files are broken into whether the
feff file came from the materials project (zip files Z=29,
missing_Cu_L2_results and missing_Cu_L3_results) or whether they were
simulated for this project (Stable_and_exp_Cu_with_results).

I'll add some notes to the readme explaining these locations! Sorry for the
confusion. Please reach out again if you have any other questions!

Best,
Sam

**Comment by Mind-Insight** [comment]
Thank you so much for responding to me! I am a student, and there are many things I don't understand yet. Now I have this question:
- Could you please explain more about how to get simulated data. I am missing the files you refer to, namely “Cu_reproducible_alignment_df_extracted_110222.joblib”. I am also missing the cache folder (as I understand it should be generated by train_RF_and_gen_data.py)

Thanks again for your help, I will definitely give you a special thanks in my work and will recommend your project

**Comment by smglsn12** [comment]
Hello! I must apologize, I thought this issue was raised in a different
repository (I just released a different module with a paper published late
last week and I've been fielding a lot of questions about that - I didn't
do my due diligence replying to you and just assumed it was that project!
I'm sorry about this). The repo you're looking at is a class project I did
(with Chloe Hsu) at the start of my PhD. IT's about 5 years old and I
haven't looked at it in quite some time. I'll poke around and see if I can
find what happened to the dataset for this if it's not available in the
repo!

Best,
Sam

**Comment by Mind-Insight** [comment]
Thank you so much for your reply, I will be very grateful to you if you do help with the problem.

**Comment by smglsn12** [comment]
The data you're looking for should be here: mhmodzoka/DT_inverse_design:
Predicting spectral emissivity of particles from a given material and
geometry using decision trees and random forest. (github.com)
<https://github.com/mhmodzoka/DT_inverse_design> I'm also a little
curious to know how you found this repo and what you're looking to use it
for!

I'll update the readme to link to a version of our reference paper that
specifies where the data is located!

Best,
Sam

**Comment by Mind-Insight** [comment]
thank you very much, I was able to get your project up and running. I was interested in this topic and found your project on the Internet, I wanted to study its work better and in general to see what will be the result of code execution, as I myself will have to write something similar in the future. Thank you very much again for your help in launching the application, I really appreciate it.
